dist: buster
branches:
  only:
   - production
   - development
   - docker
jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t wvvsupermarkt/livelane-app ./livelane/frontend
